export const DEKUFAMILY_LOAD = 'DEKUFAMILY_LOAD'
export const DEKUFAMILY_RELOAD = 'DEKUFAMILY_RELOAD'
export const DEKUFAMILY_CLEAR = 'DEKUFAMILY_CLEAR'
export const DEKUFAMILY_LOADED = 'DEKUFAMILY_LOADED'
